repos:
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      args: [--line-length=100]
      exclude: ^(bin/|doc/|scripts/)
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
        ]
      exclude: ^(bin/|doc/|scripts/|setup.py|tests/|mpitests/)
-   repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
    - id: isort
      args:
        [
          "--py",
          "312",
          "--profile",
          "black",
          "-l",
          "100",
          "-p",
          "pennylane_lightning",
          "./pennylane_lightning",
          "./mpitests",
          "./tests",
          "./scripts",
        ]
      exclude: ^(bin/|doc/|scripts/|setup.py|tests/|mpitests/)
