version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: ci_build_requirements.txt
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - cmake
    - build-essential
    - libopenblas-base
    - libopenblas-dev
    - graphviz
  jobs:
    pre_install:
      - echo "setuptools~=66.0\npip~=22.0" >> ci_build_requirements.txt
