version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: ci_build_requirements.txt
    - requirements: doc/requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - PL_BACKEND="lightning_gpu" python scripts/configure_pyproject_toml.py && SKIP_COMPILATION=True python -m build
      - rm -rf ./build && PL_BACKEND="lightning_kokkos" python scripts/configure_pyproject_toml.py && SKIP_COMPILATION=True python -m build
      - rm -rf ./build && PL_BACKEND="lightning_tensor" python scripts/configure_pyproject_toml.py && SKIP_COMPILATION=True python -m build
      - python -m pip install ./dist/*.whl
