version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true

build:
  image: latest
