version: 2

sphinx:
  configuration: doc/conf.py

python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - cmake
    - build-essential
    - libopenblas-base
    - libopenblas-dev
