version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: ci_build_requirements.txt
    - requirements: doc/requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
    - build-essential
    - libopenblas-base
    - libopenblas-dev
    - graphviz
    - wget
  jobs:
    pre_install:
      - wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb && dpkg -i cuda-keyring_1.1-1_all.deb && wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-archive-keyring.gpg && mv cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg && echo "deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/ /" | tee /etc/apt/sources.list.d/cuda-wsl-ubuntu-x86_64.list && wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin && mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
      - apt-get update
      - apt-get install cuda-toolkit
      - echo "setuptools~=66.0\npip~=22.0" >> ci_build_requirements.txt
    post_install:
      - rm -rf ./build && PL_BACKEND="lightning_kokkos" python setup.py bdist_wheel
      - rm -rf ./build && PL_BACKEND="lightning_gpu" python setup.py build_ext --define="PL_DISABLE_CUDA_SAFETY=1" && PL_BACKEND="lightning_gpu" python setup.py bdist_wheel
      - python -m pip install ./dist/*.whl
