fixes:
  - "main/::"

ignore:
  - "pennylane_lightning/src/tests"
  - "pennylane_lightning/src/gates/cpu_kernels/avx_common"

codecov:
  notify:
    after_n_builds: 4

comment:
  after_n_builds: 4

flag_management:
  # This is the default flag for all files
  default_rules:
    carryforward: true
    show_carryforward_flags: true