fixes:
  - "main/::"

codecov:
  notify:
    after_n_builds: 4

comment:
  show_carryforward_flags: true
  after_n_builds: 4
  
flag_management:
  # This is the default flag for all files
  default_rules:
    carryforward: true
