schema = 1

[device]
name = "lightning.qubit"
precision = ['float32', 'float64']

[operations]
observables = [
	"NamedObs",
	"HermitianObs",
	"TensorObs",
	"HamiltonianObs",
]

[[operations.gates]]
full = [
	"Identity",
	"PauliX",
	"PauliY",
	"PauliZ",
	"Hadamard",
	"S",
	"T",
	"PhaseShift",
	"RX",
	"RY",
	"RZ",
	"Rot",
	"CNOT",
	"CY",
	"CZ",
	"SWAP",
	"IsingXX",
	"IsingXY",
	"IsingYY",
	"IsingZZ",
	"ControlledPhaseShift",
	"CRX",
	"CRY",
	"CRZ",
	"CRot",
	"CSWAP",
	"Toffoli",
	"MultiRZ",
        "SingleExcitation",
        "SingleExcitationMinus",
        "SingleExcitationPlus",
        "DoubleExcitation",
        "DoubleExcitationMinus",
        "DoubleExcitationPlus",
]
# QubitUnitary should never be here.
# Gates in "matrix" are decomposed to QubitUnitary.
# Having a QubitUnitary here would mean an infinite loop.
matrix = [
	"OrbitalRotation",
	"MultiControlledX",
]

[measurements]
exactshots = [
	"Expval",
	"Var",
]
finiteshots = [
	"Probs",
	"Sample",
	"Measure",
]

[compilation]
qjit_compatible = false
control_flow = true
dynamic_qubit_management = false # true after merging `StateVectorLQubitDynamic` to the monorepo
