@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()

title System Context diagram for PennyLane using Lightning Qubit device

Person(developer, "Quantum software developer")

System(python, "Python", "Python 3.7+")
System(pennylane, "PennyLane", "PennyLane quantum simulation library")
System(lightning, "lightning.qubit", "PennyLane Lightning C++ simulation library ⚡")
System_Ext(tests, "Tests", "C++, CMake, Catch2")

Rel_Neighbor(developer, python, "Uses", "Win/MacOS/Lnx")

Rel_D(python, pennylane, "Uses")
Rel_U(pennylane, python, "Experiment results")

Rel_D(pennylane, lightning, "Offload operations and statevector pointer to C++ backend")
Rel_D(lightning, pennylane, "Apply C++ ops to statevector data")

Rel(tests, lightning, "Uses")

@enduml