name: Test ARM GPU runner
on:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on:
      - self-hosted
      - arm-gpu
    
    steps: 
      - run: echo "Hello, world!"
      - run: |
          cat /proc/cpuinfo
          lscpu
          
      - run: |
          source /etc/profile.d/modules.sh
          module use /opt/modules
          module load cuda/12.4
          echo "${PATH}" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          nvcc --version
          nvidia-smi