name: Clang-tidy check
on:
  pull_request:
    paths:
      - .github/workflows/tidy.yml
      - pennylane_lightning/core/src/**
      - '!pennylane_lightning/core/src/simulators/lightning_gpu/**'
      - '!pennylane_lightning/core/src/simulators/lightning_kokkos/**'
  push:
    branches:
      - master

concurrency:
  group: tidy-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tidy-cpp:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        pl_backend: ["lightning_qubit"]

    name: Tidy (C++)
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout PennyLane-Lightning
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install cmake gcc-11 g++-11 ninja-build libomp-14-dev && python -m pip install -r requirements-dev.txt
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Run clang-tidy compilation
        run: |
          cmake -BBuild -G Ninja . \
            -DENABLE_CLANG_TIDY=ON \
            -DCLANG_TIDY_BINARY=$(dirname $(which python))/clang-tidy \
            -DBUILD_TESTS=ON \
            -DENABLE_WARNINGS=ON \
            -DPL_BACKEND=${{ matrix.pl_backend }} \
            -DCMAKE_CXX_COMPILER="$(which g++-11)" \
            -DCMAKE_C_COMPILER="$(which gcc-11)"
          cmake --build ./Build
