name: Upload wheels to PyPI
on:
  workflow_run:
    workflows: ["Wheel::Linux::x86_64", "Wheel::Any::None", "Wheel::Windows::x86_64"]
    types:
      - completed

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./dist

      - name: Upload wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
