name: TestWheel::Windows::x86_64

# **What it does**: Builds python wheels for Windows (windows-latest) and store it as artifacts.
#                   Python versions: 3.7, 3.8, 3.9, 3.10.
# **Why we have it**: To build wheels for pennylane-lightning installation.
# **Who does it impact**: Wheels to be uploaded to PyPI.

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  DISTUTILS_USE_SDK: 1
  MSSdk: 1
  PYTHON3_MIN_VERSION: "7"
  PYTHON3_MAX_VERSION: "10"

jobs:
  test-win-wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        pyver: ["3.10.1", "3.10.2", "3.10.3", "3.10.4", "3.10.5", "3.10.6"]
    name: TestWheel::${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "${{ matrix.pyver }}"

      - name: Test wheel
        run: |
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pennylane-lightning
          python -m pip install git+https://github.com/PennyLaneAI/pennylane.git@master && `
          python -m pip install pytest pytest-cov pytest-mock flaky && `
          pl-device-test --device=lightning.qubit --skip-ops -x --tb=short --no-flaky-report
